// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa9X0wBwNMfKwhR0V4W_dF6O4G4KSe1dQ',
    appId: '1:17091467962:web:130012fa88414991268083',
    messagingSenderId: '17091467962',
    projectId: 'portfolio-7ee13',
    authDomain: 'portfolio-7ee13.firebaseapp.com',
    storageBucket: 'portfolio-7ee13.appspot.com',
    measurementId: 'G-TWGEHXPH1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZZ7_qVHPJeckWNxhp_jeUhGHIiGRi1PU',
    appId: '1:17091467962:android:ecfd4c6dd4629c05268083',
    messagingSenderId: '17091467962',
    projectId: 'portfolio-7ee13',
    storageBucket: 'portfolio-7ee13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWIyo8ivywMFcwmJcAvGW7wT5K9oYvEEY',
    appId: '1:17091467962:ios:0dc8406421fadb15268083',
    messagingSenderId: '17091467962',
    projectId: 'portfolio-7ee13',
    storageBucket: 'portfolio-7ee13.appspot.com',
    iosClientId: '17091467962-cv2emcs3dts2io9ha9b2sirpqe6bk5dv.apps.googleusercontent.com',
    iosBundleId: 'com.ahsailabs.portfolio',
  );
}
